export interface Equipos {
    BULTO?: number | undefined;
    CAT_DISCIPLINA?: number | undefined;
    CAT_MATL_TYPE?: string;
    CAT_TAG_NUMBER?: string;
    CAT_DESCRIPCION?: string;
    CAT_CWP?: string;
    CAT_CWP_DESCRIPCION?: string;
    CAT_CONTRATO?: string;
    CAT_DESTINO?: string;
    CAT_ESTADO?: string;
    REQ_LOG?: string;
    REQ_REQ_NUMERO?: string;
    REQ_DESCRIPCION_SUPLEMENTO?: string;
    REQ_NUMERO?: number | undefined;
    REQ_STATUS?: string;
    REQ_CANTIDAD?: number | undefined;
    REQ_TOTAL?: string;
    SOL_RFQ_NUMERO?: string;
    SOL_HITO?: string;
    SOL_ESTATUS?: string;
    SOL_FECHA?: string;
    SOL_SIG_HITO?: string;
    SOL_SIG_HITO_ESTATUS?: string;
    SOL_SIG_HITO_FECHA?: string;
    ORC_NUMERO_OC?: string;
    ORC_LINEA?: number | undefined;
    ORC_SUB_LINEA?: number | undefined;
    ORC_DESTINO?: string;
    ORC_CANTIDAD?: number | undefined;
    ORC_FECHA_RAS?: string;
    ORC_FECHA_SOP?: string;
    ORC_GRUPO_DE_EMBARQUE?: string;
    ORC_HITO?: string;
    ORC_ESTATUS?: string;
    ORC_FECHA?: string;
    ORC_SIG_HITO?: string;
    ORC_SIG_HITO_ESTATUS?: string;
    ORC_SIG_HITO_FECHA?: string;
    TB_INDEX?: number | undefined;
}
